[package]
name = "orc_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
pest = "2.7.9"
pest_derive = { version = "2.7.9", features = ["grammar-extras"] }